version: '3.7'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./storage/redis-data:/var/lib/redis/data/

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data/

  app:
    build: .
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

    env_file:
      - ./.env

    depends_on:
      - db
      - redis