# Generated by Django 3.1.6 on 2021-02-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20210214_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='members',
            new_name='member',
        ),
    ]
