# Generated by Django 3.1.6 on 2021-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_auto_20210219_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('D', 'dialogue'), ('C', 'common')], default='D', max_length=1, verbose_name='type'),
        ),
    ]
